all:
	gcc *c -o dijkstra -Wall
run: dijkstra
	./dijkstra
clear:
	rm dijkstra 
zip:
	zip dijkstra.zip main.c fila_prioridade.c fila_prioridade.h matriz_adj.c matriz_adj.h Makefile dijkstra.c dijkstra.h
